name: goast

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: goast
        uses: m-mizutani/goast-action
        with:
          policy: ./policy
          source: ./pkg
